<h2><?echo $this->survey->getName(); ?></h2>
<p class="lead">
    Bienvenido: <? echo $this->user->getName(); ?>
    <h1 id="fb-welcome"></h1>
    <br/>
    <?echo utf8_encode($this->survey->getDescription()); ?>
</p>

<?php 
$url = $this->url(array('controller' => 'index', 'action' => 'view', 'iid' => $this->user->getId()));
?>
<a class="btn btn-primary btn-lg" href="<? echo $url; ?>" role="button">
    Empezar Encuesta...
</a>