<p class="lead">
    Gracias por su participación en la encuesta<br />
    Tu Red de contactos se ha generado de la siguiente forma:
</p> 
<div id="graph">
  <div id="graph-container"></div>
  <div id="graph-info">
    <div class="pull-left margin-spacer"><div class="margin-spacer circle maroon"></div> Tu </div>
    <div class="pull-left margin-spacer"><div class="margin-spacer circle green"></div> Compañías </div>
    <div class="pull-left margin-spacer"><div class="margin-spacer circle orange"></div> Contactos </div>
  </div>
</div>

<script>
var xmlString = '<? echo $this->xml; ?>';
var parser = new DOMParser();
var doc = parser.parseFromString(xmlString, "text/xml");

sigma.parsers.gexf(doc, { 
  container: 'graph-container'
});
</script>


