<p class="lead">
    Tu Red de contactos se ha generado de la siguiente forma:
</p> 
<div id="graph">
  <div id="graph-container"></div>
  <div id="graph-info">
    <div class="pull-left margin-spacer"><div class="margin-spacer circle maroon"></div> Tu </div>
    <div class="pull-left margin-spacer"><div class="margin-spacer circle green"></div> Compañías </div>
    <div class="pull-left margin-spacer"><div class="margin-spacer circle orange"></div> Contactos </div>
  </div>
</div>

<script>
// sigma.parsers.gexf('../../gexf/gexfejm1.gexf', {
// sigma.parsers.gexf('../../gexf/arctic.gexf', {
// sigma.parsers.gexf('../../gexf/lesmiserables.gexf', {
sigma.parsers.gexf('../../gexf/report-71.gexf', { 
// sigma.parsers.gexf('../../gexf/test.gexf', { 
  container: 'graph-container'
});
</script>


