<div class="row">
  <div class="col-md-8 survey-body">
    <p class="lead"><? echo $this->block->getName(); ?></p>
    <? echo $this->form; ?>
  </div>
  <div class="col-md-4 survey-sidebar">
    <?php echo $this->partial('common/sidebar.phtml', array('blocks' => $this->blocks, 'current' => $this->current)); ?>
  </div>
</div>

<script>
$(function() {
	if($("#question_58").length ) {
		var jobs = '<? echo $this->jobs; ?>';
	    if(jobs.length > 0) {
			var availableJobs = jobs.split(',');
		    
	        $( "#question_58" ).autocomplete({
	          source: availableJobs
	        });
		}
	}
});
</script>