<div class="row">
  <div class="col-md-8 survey-body">
    <p class="lead"><? echo $this->block->getName(); ?></p>
    <? echo $this->form; ?>
  </div>
  <div class="col-md-4 survey-sidebar">
    <?php echo $this->partial('common/sidebar.phtml', array('blocks' => $this->blocks, 'current' => $this->current)); ?>
  </div>
</div>

<script>
$(function() {
	if($("#question_58").length ) {
		var jobs = "<? echo $this->jobs; ?>";
	    if(jobs.length > 0) {
			var availableJobs = jobs.split(',');
		    
	        $( "#question_58" ).autocomplete({
	          source: availableJobs
	        });
		}
	}
});

$(function() {
  if($("#question_18").length ) {
    var friends = "<? echo $this->friends; ?>";

      if(friends.length > 0) {
      var friends = friends.split(',');
        
          $( "#question_18" ).autocomplete({
            source: friends
          });
    }
  }
});

$(function() {
  if($("#question_39").length ) {
    var friends = "<? echo $this->friends; ?>";

      if(friends.length > 0) {
      var friends = friends.split(',');
        
          $( "#question_39" ).autocomplete({
            source: friends
          });
    }
  }
});
</script>