<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <h2>MÓDULO ADMINISTRADOR</h2>
        <p class="lead">Para ingresar al módulo administrador, por favor ingrese sus credenciales</p>
        <?php 
        if(strlen($this->errorMessage) != 0) {
            echo '<ul class="errors"><li>' . $this->errorMessage . '<li></ul>';
        }
        echo $this->form;
        ?>
    </div>
    <div class="col-md-3"></div>
</div>