<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Universidad del Valle</title>
    <?php 
        echo $this->headLink()->appendStylesheet('/css/global.css');
        echo $this->headLink()->appendStylesheet('/js/jquery-ui-1.11.4.custom/jquery-ui.css');        
        echo $this->headLink()->appendStylesheet('/css/bootstrap.min.css'); 
        echo $this->headScript()->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js');
        echo $this->headScript()->appendFile('/js/jquery-ui-1.11.4.custom/external/jquery/jquery.js');
        echo $this->headScript()->appendFile('/js/jquery-ui-1.11.4.custom/jquery-ui.js');
        echo $this->headScript()->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js');
        echo $this->headScript()->appendFile('/js/bootstrap.min.js');
        echo $this->headScript()->appendFile('/js/questions.js');
        echo $this->headScript()->appendFile('/js/jquery.numeric.min.js');  
    ?>
</head>
<body> 
    <div class="container">
        <div class="header">
            <img class="pull-left university-logo" src="<?=$this->baseUrl()?>/images/logoUni.png" />
            <img class="pull-right coaptar-logo" src="<?=$this->baseUrl()?>/images/coaptar.png" />
        </div>
        <div class="content">
            <?php echo $this->layout()->content ?>
        </div>
        <div class="footer">
            <img class="pull-right" src="<?=$this->baseUrl()?>/images/coaptar_trans.png" />
        </div>
     </div>
</body>
</html>