<div class="row">
    <div class="col-md-8">
        <div class="page-header">
          <h1>Administrador <small>Reporte <? echo $this->user->getName(); ?></small></h1>
          <a href="../../../gexf/report-<? echo $this->user->getId();?>.gexf">Descargar Reporte</a>
        </div>  

        <div id="graph">
          <div id="graph-container"></div>
          <div id="graph-info">
            <div class="pull-left margin-spacer"><div class="margin-spacer circle blue-main"></div> Tú </div>
            <div class="pull-left margin-spacer"><div class="margin-spacer circle blue-contact"></div> Contactos </div>
            <div class="pull-left margin-spacer"><div class="margin-spacer circle blue-company"></div> Compañías </div>
          </div>
        </div>
        
    </div>
    <div class="col-md-4">
        <?php echo $this->partial('common/user-stats.phtml', array('stats' => $this->stats)); ?>
    </div>
</div>



<script>
// sigma.parsers.gexf('../../gexf/gexfejm1.gexf', {
// sigma.parsers.gexf('../../gexf/arctic.gexf', {
// sigma.parsers.gexf('../../gexf/lesmiserables.gexf', {
// sigma.parsers.gexf('../../gexf/test.gexf', { 
sigma.parsers.gexf('../../../gexf/report-<? echo $this->user->getId(); ?>.gexf', { 
  container: 'graph-container'
});
</script>


