<div class="row">
    <div class="col-md-8">
        <div class="page-header">
          <h1>Administrador <small>Encuestados</small></h1>
        </div>
        <?php echo $this->partial('common/user-table.phtml', array('users' => $this->users)); ?>
    </div>
    <div class="col-md-4">
        <?php echo $this->partial('common/user-stats.phtml', array('stats' => $this->stats)); ?>
    </div>
</div>