<? $url = $this->url(array('controller' => 'admin', 'action' => 'gexf', 'iid' => $this->user->getId())); ?>
<div class="row">
    <div class="col-md-8">
        <div class="page-header">
          <h1>Administrador <small>Resultados</small></h1>
        </div>  
        <p><strong>Nombre: </strong><?php echo $this->user->getName(); ?></p>
        <p><strong>Estado de la Encuesta: </strong>
            <?php if($this->user->hasFinishedSurvey()) {?>
                    <span class="label label-success">Finalizado</span>
            <?php } else { ?>
                    <span class="label label-warning">Incompleto</span>
            <?php }?>  
        </p>
        <p><strong>Fecha de Inicio de la Encuesta: </strong>
            <?php echo $this->user->getStartDate(true); ?>
        </p>
        <p><strong>Fecha de Finalización de la Encuesta: </strong>
            <?php echo $this->user->getFinishDate(true); ?>
        </p>
        <p><strong>Reporte GEXF: </strong>           
            <? if($this->user->hasReport()) { ?>
                <a href="<?php echo $url; ?>">
                    <button type="button" class="btn btn-primary btn-xs">
                        Ver
                    </button>
                </a>
            <? } else { ?>
                El reporte estará disponible cuando el usuario termine de diligenciar el formulario
            <? } ?>            
        </p>
        <?php echo $this->partial('common/user-responses.phtml', array('survey' => $this->survey, 
                                                                       'userData' => $this->userData)); ?>
    </div>
    <div class="col-md-4">
        <?php echo $this->partial('common/user-stats.phtml', array('stats' => $this->stats)); ?>
    </div>
</div>